name: Build frontend app and deploy

#defaults:
#  run:
#    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
      - frontend 

jobs:
  BuildAndDeploy:
    name: Build frontend
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: test apicacao
      run: |
          ng test 
    
    - name: build frontend
      run: |
          sudo apt-get update && sudo apt-get -y install npm
          sudo npm install -g @angular/cli
          cd frontend
          docker build . -t frontend 


