name: Build frontend app and deploy

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
      - frontend 

jobs:
  BuildAndDeploy:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: dependencias
      run: |
          sudo apt-get update && sudo apt-get -y install npm
          sudo npm install -g @angular/cli
     
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_TOKEN }}
    
    - name: Build and push image
      run: |
        docker build -t ghcr.io/schnand/frontend-app:latest .
        docker push ghcr.io/schnand/frontend-app:latest 
     
    #- name: build frontend
    #  run: |
    #      cd frontend
    #      docker build . -t frontend 


