name: Build frontend app and deploy

#defaults:
#  run:
#    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
      - frontend
  #  paths:
   # - 'frontend/**'  

jobs:
  BuildAndDeploy:
    name: Build frontend
    runs-on: self-hosted
    steps:
    - name: build frontend
      run: |
          sudo apt-get update && sudo apt-get -y install npm
          sudo npm install -g @angular/cli
          docker build -t frontend https://github.com/schnand/bootcamp-itau-ada/tree/frontend/frontend

    - name: Test frontend
      run: |
          ng test 
          ##

